### ISSUE TITLE
How to add preview image to player 

### ISSUE THREAD

**Issue by alurei97** [jhomlala/betterplayer#107]
I want to show a picture before the play button is pressed. 
I'm trying to use a placeholder like this:
```
BetterPlayerConfiguration(
   placeholder: Image.network( '<url>' ),
   fit: BoxFit.contain,
)
```
The problem is, after video starts, the placeholder stays as background and I can see it because the video is streched out:
![placeholder](https://user-images.githubusercontent.com/23730052/97510566-4beb7900-1985-11eb-9ca6-53eda6b12a24.png)

Notice that it's `BoxFit.contain` so the video isn't distorted and that's why I can see the placeholder as background (I have tried all `BoxFit' and it distorts the video or I can see the placeholder). Maybe it's an aspect radio problem?

Any way to hide it when the video starts?

**Comment by jhomlala** [comment]
@alurei97 Can you share your example? From my perspective, there's something wrong with your aspect ratio values.
Here is an example which works fine with 16/9 videos:
```dart return Scaffold(
      appBar: AppBar(
        title: Text("Other page"),
      ),
      body: AspectRatio(
        aspectRatio: 16/9,
        child: BetterPlayer.network(
          "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
          betterPlayerConfiguration: BetterPlayerConfiguration(
            aspectRatio: 16/9,
            fit: BoxFit.contain,
            placeholder: Image.network("https://api.time.com/wp-content/uploads/2020/01/BigCatsPerfume.jpg")
          ),
        ),
      ),
    );```

**Comment by alurei97** [comment]
I have `aspectRatio: 16/9` but the video isn't. 

Maybe I didn't explain correctly:
I want the placeholder to show up _until_ Play is pressed (now the image shows up until the video loads completely, after that, the placeholder shows up as background because of video aspect ratio). 

I also want to hide the placeholder when Play is pressed. (Would the image hide if video's aspect ratio and player's aspectRatio are 16:9?)

**Comment by jhomlala** [comment]
@alurei97 Please upgrade Better Player to 0.0.31. You should be able to use showPlaceholderUntilPlay parameter in BetterPlayerConfiguration. This should solve your issue.

**Comment by alurei97** [comment]
`showPlaceholderUntilPlay` works perfectly.

Now, how can I hide placeholder (to fix being as brackground when aspect ratios are different) when Play is pressed? Can I access the placeholder to hide it from my code when I detect play event?

**Comment by jhomlala** [comment]
Have you tried using event listener? You should be able to use PLAY event which is triggered when play button is pressed.
https://github.com/jhomlala/betterplayer#listen-to-video-events

**Comment by alurei97** [comment]
I know what are listeners but I can't do something like this:
```
betterPlayerController.addEventsListener((event){
      if (event.betterPlayerEventType == "PLAY") {
        betterPlayerController.betterPlayerConfiguration.placeholder = Image(...);
      }
    });
```
Error: `'placeholder' can't be used as a setter because it's final.
Try finding a different setter, or making 'placeholder' non-final.`

**Comment by jhomlala** [comment]
@alurei97 Use Image placeholder wrapped in StreamBuilder. Here is an example:
```dart
import 'dart:async';

import 'package:better_player/better_player.dart';
import 'package:better_player_example/constants.dart';
import 'package:flutter/material.dart';

class NormalPlayerPage extends StatefulWidget {
  @override
  _NormalPlayerPageState createState() => _NormalPlayerPageState();
}

class _NormalPlayerPageState extends State<NormalPlayerPage> {
  BetterPlayerController _betterPlayerController;
  StreamController<bool> _placeholderStreamController =
      StreamController.broadcast();

  @override
  void dispose() {
    _placeholderStreamController.close();
    super.dispose();
  }

  @override
  void initState() {
    BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
      aspectRatio: 1,
      fit: BoxFit.cover,
      placeholder: _buildVideoPlaceholder(),
      showPlaceholderUntilPlay: true,
    );
    BetterPlayerDataSource dataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.NETWORK, Constants.forBiggerBlazesUrl);
    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    _betterPlayerController.setupDataSource(dataSource);
    _betterPlayerController.addEventsListener((event) {
      if (event.betterPlayerEventType == BetterPlayerEventType.PLAY){
        _placeholderStreamController.add(true);
      }
    });
    super.initState();
  }

  
  ///Use stream builder to show image placeholder when video is not played for
  ///first time. Once user clicks first time on play, placeholder will be dismissed.
  Widget _buildVideoPlaceholder() {
    return StreamBuilder<bool>(
      stream: _placeholderStreamController.stream,
      builder: (context, snapshot) {
        return snapshot.data ?? false
            ? const SizedBox()
            : Image.network(
                "https://imgix.bustle.com/uploads/image/2020/8/5/23905b9c-6b8c-47fa-bc0f-434de1d7e9bf-avengers-5.jpg");
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Normal player"),
      ),
      body: Column(
        children: [
          const SizedBox(height: 8),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Text(
              "Normal player with configuration managed by developer.",
              style: TextStyle(fontSize: 16),
            ),
          ),
          AspectRatio(
            aspectRatio: 1,
            child: BetterPlayer(controller: _betterPlayerController),
          ),
        ],
      ),
    );
  }
}

```

**Comment by alurei97** [comment]
Now it's working as I expected, thanks!

**Comment by alurei97** [comment]
Hello again, I've found an issue with your example code: when the player is normal, the image hides perfectly and the video starts, but if I go to fullscreen, sometimes the image reappears while the video keeps playing (I have to pause then play to hide it again). Do you have any idea in how to fix this? Thanks for all your big help with my project <3

**Comment by jhomlala** [comment]
Fixed in Better Player 0.0.34.

**Comment by alurei97** [comment]
0.0.34 didn't fix it unfortunately. I'm using `_placeholderStreamController` example code from above, but when I tap fullscreen button, the image goes to the background (same problem I had when not using `_placeholderStreamController` without fullscreen). Thanks again for your effort.

**Comment by jhomlala** [comment]
I agree, there was another case which wasn't handled. Please try new version: 0.0.35.

**Comment by alurei97** [comment]
I just tried it but it's not working 100% of the times I go to fullscreen, only sometimes. It's random, sometimes it's completely hidden, sometimes it's set as a background (as I told you in my previous message).

**Comment by jhomlala** [comment]
@alurei97 what's the scenario when it doesn't work? can you reproduce it?

**Comment by alurei97** [comment]
I'm using the code you posted a while ago. I go to fullscreen and go back several times, and sometimes the image it's hidden, sometimes I can see it as background behind the video, it seems random.

**Comment by jhomlala** [comment]
@alurei97 can you recheck it with latest version?

**Comment by alurei97** [comment]
For now, I have tried 0.0.41 in Android, still not working 100%:
- if the video is paused and I go to fullscreen, sometimes the image is hidden, when it's not it hides when I click on play (this behavior could be enough)
- if the video is playing and I go to fullscreen, sometimes the image is hidden, when it's not, it hides when I pause and then click on play

**Comment by jhomlala** [comment]
@alurei97 Tried this code in the latest version (0.0.42) on Android on 2 different devices and everything seems to be ok. Maybe you can share your example which can be reproduced on my side?

```dart
import 'dart:async';

import 'package:better_player/better_player.dart';
import 'package:better_player_example/constants.dart';
import 'package:flutter/material.dart';

class NormalPlayerPage extends StatefulWidget {
  @override
  _NormalPlayerPageState createState() => _NormalPlayerPageState();
}

class _NormalPlayerPageState extends State<NormalPlayerPage> {
  BetterPlayerController _betterPlayerController;
  StreamController<bool> _placeholderStreamController =
      StreamController.broadcast();

  @override
  void dispose() {
    _placeholderStreamController.close();
    super.dispose();
  }

  @override
  void initState() {
    BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
      aspectRatio: 1,
      fit: BoxFit.cover,
      placeholder: _buildVideoPlaceholder(),
      showPlaceholderUntilPlay: true,
    );
    BetterPlayerDataSource dataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.NETWORK, Constants.forBiggerBlazesUrl);
    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    _betterPlayerController.setupDataSource(dataSource);
    _betterPlayerController.addEventsListener((event) {
      if (event.betterPlayerEventType == BetterPlayerEventType.PLAY){
        _placeholderStreamController.add(true);
      }
    });
    super.initState();
  }

  
  ///Use stream builder to show image placeholder when video is not played for
  ///first time. Once user clicks first time on play, placeholder will be dismissed.
  Widget _buildVideoPlaceholder() {
    return StreamBuilder<bool>(
      stream: _placeholderStreamController.stream,
      builder: (context, snapshot) {
        return snapshot.data ?? false
            ? const SizedBox()
            : Image.network(
                "https://imgix.bustle.com/uploads/image/2020/8/5/23905b9c-6b8c-47fa-bc0f-434de1d7e9bf-avengers-5.jpg");
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Normal player"),
      ),
      body: Column(
        children: [
          const SizedBox(height: 8),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Text(
              "Normal player with configuration managed by developer.",
              style: TextStyle(fontSize: 16),
            ),
          ),
          AspectRatio(
            aspectRatio: 1,
            child: BetterPlayer(controller: _betterPlayerController),
          ),
        ],
      ),
    );
  }
}```

**Comment by alurei97** [comment]
Could you try one of my videos? I think the problem is they aren't 16:9.

It would be:
```
BetterPlayerDataSource dataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.NETWORK, http://www.documentarymania.org/video_flutter.php?title=Gravity);
``
I also have: `fit: BoxFit.contain`

**Comment by jhomlala** [comment]
@alurei97 try this:
```dart
import 'dart:async';

import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';

class NormalPlayerPage extends StatefulWidget {
  @override
  _NormalPlayerPageState createState() => _NormalPlayerPageState();
}

class _NormalPlayerPageState extends State<NormalPlayerPage> {
  BetterPlayerController _betterPlayerController;
  StreamController<bool> _placeholderStreamController =
      StreamController.broadcast();
  bool _showPlaceholder = true;

  @override
  void dispose() {
    _placeholderStreamController.close();
    super.dispose();
  }

  @override
  void initState() {
    BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
      fit: BoxFit.contain,
      placeholder: _buildVideoPlaceholder(),
      showPlaceholderUntilPlay: true,
    );
    BetterPlayerDataSource dataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        "http://www.documentarymania.org/video_flutter.php?title=Gravity");
    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    _betterPlayerController.setupDataSource(dataSource);
    _betterPlayerController.addEventsListener((event) {
      if (event.betterPlayerEventType == BetterPlayerEventType.play) {
        _setPlaceholderVisibleState(false);
      }
    });
    super.initState();
  }

  void _setPlaceholderVisibleState(bool hidden) {
    _placeholderStreamController.add(hidden);
    _showPlaceholder = hidden;
  }

  ///_placeholderStreamController is used only to refresh video placeholder
  ///widget.
  Widget _buildVideoPlaceholder() {
    return StreamBuilder<bool>(
      stream: _placeholderStreamController.stream,
      builder: (context, snapshot) {
        return _showPlaceholder
            ? Image.network(
                "https://imgix.bustle.com/uploads/image/2020/8/5/23905b9c-6b8c-47fa-bc0f-434de1d7e9bf-avengers-5.jpg",
              )
            : const SizedBox();
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Normal player"),
      ),
      body: Column(
        children: [
          const SizedBox(height: 8),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Text(
              "Normal player with configuration managed by developer.",
              style: TextStyle(fontSize: 16),
            ),
          ),
          AspectRatio(
            aspectRatio: 16 / 9,
            child: BetterPlayer(
              controller: _betterPlayerController,
            ),
          ),
        ],
      ),
    );
  }
}

```

**Comment by alurei97** [comment]
With your last code it's working 100% on Android with both versions 0.0.42 and 0.0.43. Thanks again!

I suggest you to add this code to Readme or somewhere else because it can be a very demanded customization.

**Comment by alurei97** [comment]
I confirm it's working 100% on iOS too.

**Comment by jhomlala** [comment]
@alurei97 Ok, added this code to examples.
