### ISSUE TITLE
[BUG] 'Video Can't Be Played' error missing when streaming and internet connection is lost in iOS

### ISSUE THREAD

**Issue by rc8marcelo** [jhomlala/betterplayer#153]
**Describe the bug**
The error state or screen that shows an ! icon with a message "Video can't be played" doesn't show up on iOS when you stream a video and try to navigate or watch through an unloaded portion of the video

**To Reproduce**
1. Setup BetterPlayer to use a `.NETWORK` datasource
2. Upon loading a part of the video, turn off your wi-fi
3. Either watch until the part where it isn't stream or navigate/seek to it with the progress indicator circle
4. Verify the behavior shown in the screenshot below

**Expected behavior**
Rather than the error screen showing up (this is what happens on Android), on iOS devices we are just presented with a black `CircularProgressIndicator`. 

**Screenshots**
![image](https://user-images.githubusercontent.com/341493/100493386-57db7e00-3171-11eb-8408-491445db75c9.png)

Video: https://drive.google.com/file/d/1K8Jxuh1tbLcmgaImAcGhVB06ZtFBEZoQ/view?usp=sharing

**Flutter doctor**
![image](https://user-images.githubusercontent.com/341493/100493390-645fd680-3171-11eb-813d-639cc56b7604.png)

**Better Player version**
- Version: 0.0.35

**Smartphone (please complete the following information):**
 - Device: iPhone 6 / iPhone 6S Plus
 - OS: iOS 12 / iOS 13

**Additional context**
This works properly on Android. 

**Workaround if someone needs it**
In case anyone needs this functionality, my workaround for ios is to replace the `BetterPlayerController`'s datasource into a non-existent local file so that it goes into an error state.  I just hide the progress of the previous video if I need to play it in some future point of time. For Android, you can either let the player play up to the part where it was streamed or try to reload the datasource from network if you want to force the error state immediately.

**Comment by huxaiphaer** [comment]
Hey @rc8marcelo . did you get a solution for this ? It's really a big issue

**Comment by jhomlala** [comment]
Fixed in BetterPlayer 0.0.44.

**Comment by maximevo** [comment]
Hey there,

I have the same issue, on Android. 

I have pulled the latest release, but I still get the same error, on Android.

Is that expected ? 

Thank you,
Maxime
