### ISSUE TITLE
[BUG] The getter 'notificationConfiguration' was called on null.

### ISSUE THREAD

**Issue by m1n093** [jhomlala/betterplayer#307]
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'notificationConfiguration' was called on null.

I have the error when i just add BetterPlayer without BetterPlayerDataSource

E/flutter (18643): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'notificationConfiguration' was called on null.
E/flutter (18643): Receiver: null
E/flutter (18643): Tried calling: notificationConfiguration
E/flutter (18643): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (18643): #1      BetterPlayerController.onPlayerVisibilityChanged (package:better_player/src/core/better_player_controller.dart:710:34)
E/flutter (18643): #2      _BetterPlayerState._buildPlayer.<anonymous closure> (package:better_player/src/core/better_player.dart:267:29)
E/flutter (18643): #3      VisibilityDetectorLayer._fireCallback (package:visibility_detector/src/visibility_detector_layer.dart:268:24)
E/flutter (18643): #4      VisibilityDetectorLayer._processCallbacks (package:visibility_detector/src/visibility_detector_layer.dart:239:13)
E/flutter (18643): #5      _TaskEntry.run.<anonymous closure> (package:flutter/src/scheduler/binding.dart:80:34)
E/flutter (18643): #6      Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (18643): #7      _TaskEntry.run (package:flutter/src/scheduler/binding.dart:77:16)
E/flutter (18643): #8      SchedulerBinding.handleEventLoopCallback (package:flutter/src/scheduler/binding.dart:460:15)
E/flutter (18643): #9      SchedulerBinding._runTasks (package:flutter/src/scheduler/binding.dart:438:9)
E/flutter (18643): #10     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (18643): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (18643): #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (18643): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (18643): #14     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (18643): #15     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (18643): #16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (18643): #17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (18643): #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (18643): #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (18643): #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (18643): 

**Expected behavior**
I want initialize BetterPlayer without dataSource. I want do it in next step. I want receive player with blank page.

**Better Player version**
- Version: better_player: ^0.0.53

**Comment by chmiguel** [comment]
I'm experiencing the same issue.

**Comment by Sahil-Colco** [comment]
Same issue!

**Comment by jhomlala** [comment]
Fixed in 0.0.56.

**Comment by bounty1342** [comment]
```
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown during a platform message callback:
flutter: The getter 'showNotification' was called on null.
flutter: Receiver: null
flutter: Tried calling: showNotification
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
flutter: #1  BetterPlayerController.setAppLifecycleState        package:better_player/…/core/better_player_controller.dart:788
flutter: #2  _BetterPlayerState.didChangeAppLifecycleState   package:better_player/…/core/better_player.dart:277
flutter: #3  WidgetsBinding.handleAppLifecycleStateChanged  package:flutter/…/widgets/binding.dart:704
flutter: #4   ServicesBinding._handleLifecycleMessage package:flutter/…/services/binding.dart:192
flutter: #5  BasicMessageChannel.setMessageHandler.<anonymous closure> package:flutter/…/services/platform_channel.dart:74
flutter: #6  BasicMessageChannel.setMessageHandler.<anonymous closure> package:flutter/…/services/platform_channel.dart:73
flutter: #7  _DefaultBinaryMessenger.handlePlatformMessage  package:flutter/…/services/binding.dart:283
flutter: #8  _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
flutter: #12 _invoke3 (dart:ui/hooks.dart:279:10)

```

@jhomlala, this issue is still present with named constructors.
