### ISSUE TITLE
[BUG] AutoPlay & fullScreenByDefault causes error

### ISSUE THREAD

**Issue by themadmrj** [jhomlala/betterplayer#354]
**Describe the bug**

When loading a video with `autoPlay = true` and `fullScreenByDefault = true`, I get the following error report:

```
════════ Exception caught by foundation library ════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for VideoPlayerController:
setState() or markNeedsBuild() called when widget tree was locked.

This BetterPlayerMaterialControls widget cannot be marked as needing to build because the framework is locked.
The widget on which setState() or markNeedsBuild() was called was: BetterPlayerMaterialControls
  dependencies: [BetterPlayerControllerProvider]
  state: _BetterPlayerMaterialControlsState#38fa7
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4297:9)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4307:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1264:14)
#3      _BetterPlayerMaterialControlsState._updateState (package:better_player/src/controls/better_player_material_controls.dart:663:9)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
...
The VideoPlayerController sending notification was: VideoPlayerController#28285(VideoPlayerValue(duration: 0:00:03.005000, size: Size(360.0, 640.0), position: 0:00:00.000000, absolutePosition: null, buffered: [DurationRange(start: 0:00:00.000000, end: 0:00:00.000000)], isPlaying: false, isLooping: true, isBuffering: false, volume: 1.0, errorDescription: null))
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by foundation library ════════════════════════════════════════════════════
setState() or markNeedsBuild() called when widget tree was locked.

```

If I try commenting that specific call of setState out, another one pops up from somewhere else in the library. This is a new error, since it my code used to work but now that I tested again (and haven't changed anything), it doesn't work anymore. Sadly I cannot say as of which version of BetterPlayer this didn't work anymore.

**Steps to reproduce the behavior:**

1. Configure `BetterPlayerConfiguration` with  `autoPlay = true` and `fullScreenByDefault = true`
2. SetupDataSource
3. The error will occur now

<details>
  <summary>**Flutter doctor**</summary>
  
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.804], locale fr-FR)
    • Flutter version 1.22.6 at E:\Flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\MrJ\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at E:\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
</details>

**Better Player version**

0.0.60

**Additional context**

I'm sorry I keep reporting bugs. I think you're doing an amazing job, thank you!!!

**Comment by schisms** [comment]
I have both autoPlay and fullscreenBydefault enabled, and just upgraded to the latest version. No issues on my side.

**Comment by themadmrj** [comment]
What's your setup?

Here is my Widget. I navigate to this screen when the user taps a thumbnail of the video, to start playing the video in fullscreen. This does not work for me.

```
class VideoScreenArgs {
  final String url;
  final File file;

  VideoScreenArgs({this.url, this.file});
}

class VideoFullScreen extends StatefulWidget {
  final VideoScreenArgs args;

  VideoFullScreen({@required this.args})
      : assert(args.url != null || args.file != null,
            "either url or file must be provided");

  @override
  _VideoFullScreenState createState() => _VideoFullScreenState();
}

class _VideoFullScreenState extends State<VideoFullScreen> {
  BetterPlayerController _controller;

  bool didPop = false;

  @override
  void initState() {
    super.initState();

    _controller =  BetterPlayerController(BetterPlayerConfiguration(
        autoDetectFullscreenDeviceOrientation: true,
        fit: BoxFit.contain,
        autoPlay: true,
        looping: true,
        fullScreenByDefault: true,
        deviceOrientationsOnFullScreen: [
          DeviceOrientation.portraitUp,
          DeviceOrientation.portraitDown,
          DeviceOrientation.landscapeLeft,
          DeviceOrientation.landscapeRight
        ],
        deviceOrientationsAfterFullScreen: [
          DeviceOrientation.portraitUp,
          DeviceOrientation.portraitDown
        ],
        controlsConfiguration: BetterPlayerControlsConfiguration(
            enableOverflowMenu: false, enableSkips: false),
      ));
    

    setVolume();

    //load video once headers are obtained if loading from network and not locally
    if (widget.args.file == null) {
      serviceLocator<FireBaseInterceptor>().getAuthHeaders().then((headers) {
        BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
            BetterPlayerDataSourceType.network, widget.args.url,
            headers: headers);
        _controller.setupDataSource(betterPlayerDataSource);
      });
    } else {
      final dataSource = BetterPlayerDataSource(
          BetterPlayerDataSourceType.file, widget.args.file.path);
      _controller.setupDataSource(dataSource);
    }

    _controller.addEventsListener((event) {
      if (event.betterPlayerEventType == BetterPlayerEventType.hideFullscreen) {
        if (!didPop) {
          didPop = true;
          serviceLocator<NavigationService>().pop();
        }
      } else if (event.betterPlayerEventType ==
          BetterPlayerEventType.setVolume) {
        MediaHandler.updateVolumePrefs(event.parameters["volume"]);
      }
    });
  }

  void setVolume() =>
      MediaHandler.volume.then((value) => _controller?.setVolume(value));

  @override
  Widget build(BuildContext context) {
    return BetterPlayer(controller: _controller);
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}
```

**Comment by schisms** [comment]
` _controller = BetterPlayerController(
      BetterPlayerConfiguration(
        autoPlay: true,
        autoDispose: false,
        looping: true,
        fullScreenByDefault: true,
        allowedScreenSleep: false,
        controlsConfiguration: BetterPlayerControlsConfiguration(
            playerTheme: _playerTheme,
            enableProgressBar: true,
            customControlsBuilder: (controller) => CustomControlsWidget(
                  controller: controller,
                )),
      ),
    );
    _controller.setupDataSource(dataSource);
    _controller.setLooping(true);`

widget build: 
`return WillPopScope(
      onWillPop: _onWillPop,
      child: MaterialApp(
        home: Scaffold(
          body: FutureBuilder(
              future: _initalizeVideoPlayerFuture,
              builder: (context, snapshot) {
                return Center(
                  child: AspectRatio(
                    aspectRatio: 16 / 9,
                    child: BetterPlayer(controller: _controller),
                  ),
                );
              }),
        ),
      ),
    );
  }`

(The on will pop is just to handle back button)

I also use a custom theme with zero controls. It's all tap feedback to play/pause/quit. 

Your problem may be that you're building the widget while build method is still being called. I believe it's either how you're popping to the video screen, or you may need to try and replicate my build function with a future.

Disclaimer: I started flutter 19 days ago and have no idea what I am doing

**Comment by themadmrj** [comment]
The BetterPlayer docs don't state that any `FutureBuilder` is required. I don't think that's the case.

> I believe it's either how you're popping to the video screen

I also tried removing the "pop" statement, which did not remove the problem. However, the exact same setup with autoPlay = false removes the problem, but I have to click the fullscreen icon, which defeats the purpose...

**Comment by schisms** [comment]
Use an event handler and have it full screen on play? 

Really unsure. I wonder if the theme has to do with it, because the theme has to be built. I use a custom theme.

theme.dart
`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:better_player/better_player.dart';
import 'package:velocity_x/velocity_x.dart';
import 'dialog.dart';
// ignore: unused_import
//import 'package:better_player/src/controls/better_player_controls_state.dart';

// ignore: unused_import
import 'dart:async';

// ignore: unused_element
bool _wasLoading = false;

class CustomControlsWidget extends StatefulWidget {
  final BetterPlayerController controller;

  const CustomControlsWidget({Key key, this.controller}) : super(key: key);

  @override
  _CustomControlsWidgetState createState() => _CustomControlsWidgetState();
}

class _CustomControlsWidgetState extends State<CustomControlsWidget> {
  @override
  Widget build(BuildContext context) {
    if (widget.controller.videoPlayerController.value.hasError == true) {
      return Container(
        color: Colors.black,
        child: _buildErrorWidget(),
      );
    }
    _wasLoading = isLoading(widget.controller.videoPlayerController.value);

    return GestureDetector(
        behavior: HitTestBehavior.translucent,
        onDoubleTap: () {
          var dialog = CustomAlertDialog(
              title: "Exit Session?",
              message: "Are you sure?",
              onPostivePressed: () async {
                SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
                SystemChrome.setPreferredOrientations([
                  DeviceOrientation.portraitDown,
                  DeviceOrientation.portraitUp,
                ]);
                try {
                  await widget.controller.pause();
                } catch (ex) {}

                Navigator.of(context)
                    .popUntil((Route<dynamic> route) => route.isFirst);
              },
              positiveBtnText: 'Yes',
              negativeBtnText: 'No');
          showDialog(
              context: context, builder: (BuildContext context) => dialog);
        },
        onTap: () {
          setState(() {
            if (widget.controller.isPlaying())
              widget.controller.pause();
            else
              widget.controller.play();
          });
        },
        child: Column(
          children: [
            if (_wasLoading)
              Center(child: _buildLoadingWidget())
            else
              SizedBox.shrink()
          ],
        ));
  }

  Widget _buildErrorWidget() {
    final errorBuilder =
        widget.controller.betterPlayerConfiguration.errorBuilder;
    if (errorBuilder != null) {
      return errorBuilder(context,
          widget.controller.videoPlayerController.value.errorDescription);
    } else {
      final textStyle = TextStyle(color: Colors.white);
      return Center(
        child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
          Icon(
            Icons.warning,
            color: Colors.red,
            size: 42,
          ),
          Text(
            widget.controller.translations.generalDefaultError,
            style: textStyle,
          ),
          TextButton(
            onPressed: () {
              widget.controller.retryDataSource();
            },
            child: Text(
              widget.controller.translations.generalRetry,
              style: textStyle.copyWith(fontWeight: FontWeight.bold),
            ),
          )
        ]),
      );
    }
  }
}

// ignore: unused_element
Widget _buildLoadingWidget() {
  return CircularProgressIndicator(
    valueColor: AlwaysStoppedAnimation<Color>(Colors.red ?? Colors.blue),
    backgroundColor: Colors.purple,
  );
}

bool isLoading(VideoPlayerValue latestValue) {
  if (latestValue != null) {
    if (!latestValue.isPlaying && latestValue.duration == null) {
      return true;
    }

    final Duration position = latestValue.position;
    print(latestValue.position.toString());
    Duration bufferedEndPosition;
    if (latestValue.buffered?.isNotEmpty == true) {
      bufferedEndPosition = latestValue.buffered.last.end;
    }

    if (position != null && bufferedEndPosition != null) {
      final difference = bufferedEndPosition - position;

      if (latestValue.isPlaying &&
          latestValue.isBuffering &&
          difference.inMilliseconds < 20000) {
        return true;
      }
    }
  }
  return false;
}
`

NOTE there is no loading screen in this theme, I am fixing it today

**Comment by themadmrj** [comment]
As I mentioned in my post, this exact code used to work in a previous version of better_player. Therefore, it makes no sense having to implement workarounds for a regression.

**Comment by jhomlala** [comment]
Should be fixed in 0.0.61.

**Comment by themadmrj** [comment]
> Should be fixed in 0.0.61.

It did fix that issue, but when I exit fullscreen, I get:

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
A BetterPlayerController was used after being disposed.

Once you have called dispose() on a BetterPlayerController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:178:12)
#3      _BetterPlayerWithControlsState.dispose (package:better_player/src/core/better_player_with_controls.dart:60:23)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4854:12)
```

I tried delaying the pop line, from `serviceLocator<NavigationService>().pop();` to:
```
WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
  serviceLocator<NavigationService>().pop();
});
```

But it still happens around 40% of the time. Any idea how to fix it?

**Comment by themadmrj** [comment]
> Should be fixed in 0.0.61.

It did fix that issue, thank you!! However, when I exit fullscreen, I get the following error:
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
A BetterPlayerController was used after being disposed.

Once you have called dispose() on a BetterPlayerController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:178:12)
#3      _BetterPlayerWithControlsState.dispose (package:better_player/src/core/better_player_with_controls.dart:60:23)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4854:12)
```
<details>
  <summary>**My Widget above**</summary>

```
class VideoScreenArgs {
  final String url;
  final File file;

  VideoScreenArgs({this.url, this.file});
}

class VideoFullScreen extends StatefulWidget {
  final VideoScreenArgs args;

  VideoFullScreen({@required this.args})
      : assert(args.url != null || args.file != null,
            "either url or file must be provided");

  @override
  _VideoFullScreenState createState() => _VideoFullScreenState();
}

class _VideoFullScreenState extends State<VideoFullScreen> {
  BetterPlayerController _controller;

  bool didPop = false;

  @override
  void initState() {
    super.initState();

    _controller =  BetterPlayerController(BetterPlayerConfiguration(
        autoDetectFullscreenDeviceOrientation: true,
        fit: BoxFit.contain,
        autoPlay: true,
        looping: true,
        fullScreenByDefault: true,
        deviceOrientationsOnFullScreen: [
          DeviceOrientation.portraitUp,
          DeviceOrientation.portraitDown,
          DeviceOrientation.landscapeLeft,
          DeviceOrientation.landscapeRight
        ],
        deviceOrientationsAfterFullScreen: [
          DeviceOrientation.portraitUp,
          DeviceOrientation.portraitDown
        ],
        controlsConfiguration: BetterPlayerControlsConfiguration(
            enableOverflowMenu: false, enableSkips: false),
      ));
    

    setVolume();

    //load video once headers are obtained if loading from network and not locally
    if (widget.args.file == null) {
      serviceLocator<FireBaseInterceptor>().getAuthHeaders().then((headers) {
        BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
            BetterPlayerDataSourceType.network, widget.args.url,
            headers: headers);
        _controller.setupDataSource(betterPlayerDataSource);
      });
    } else {
      final dataSource = BetterPlayerDataSource(
          BetterPlayerDataSourceType.file, widget.args.file.path);
      _controller.setupDataSource(dataSource);
    }

    _controller.addEventsListener((event) {
      if (event.betterPlayerEventType == BetterPlayerEventType.hideFullscreen) {
        if (!didPop) {
          didPop = true;
          serviceLocator<NavigationService>().pop();
        }
      } else if (event.betterPlayerEventType ==
          BetterPlayerEventType.setVolume) {
        MediaHandler.updateVolumePrefs(event.parameters["volume"]);
      }
    });
  }

  void setVolume() =>
      MediaHandler.volume.then((value) => _controller?.setVolume(value));

  @override
  Widget build(BuildContext context) {
    return BetterPlayer(controller: _controller);
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}
```
</details>

In my Widget, I tried removing `_controller.dispose();` so autoDispose is set to `true`, but it didn't help. Then I tried replacing `serviceLocator<NavigationService>().pop();` with this:
```
WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
  serviceLocator<NavigationService>().pop();
});
```
But the error still arrises about 40% of the time. Any idea how to fix it?

**Comment by themadmrj** [comment]
Tested, it works fine now, thanks !
