### ISSUE TITLE
Video plays during an incoming phone call[BUG]

### ISSUE THREAD

**Issue by ThangNguyen91** [jhomlala/betterplayer#381]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

**Describe the bug**
Video plays during an incoming phone call
**To Reproduce**
1. Open Video
2. Call incoming
3. Click listen
4. Video continue play

**Example code*
`import 'package:audio_service/audio_service.dart';
import 'package:better_player/better_player.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:wakelock/wakelock.dart';

class CustomVideoForTrailerPage extends StatefulWidget {

  CustomVideoForTrailerPage();

  @override
  State<StatefulWidget> createState() {
    return _CustomVideoForTrailerPageState();
  }
}

class _CustomVideoForTrailerPageState extends State<CustomVideoForTrailerPage>
    with WidgetsBindingObserver {
  BetterPlayerController _betterPlayerController;
  BetterPlayerEventType type;

  @override
  void initState() {
    super.initState();
    if (AudioService?.playbackState?.playing ?? false) AudioService.pause();
    SystemChrome.setEnabledSystemUIOverlays([]);
    Wakelock.enable();
    WidgetsBinding.instance.addObserver(this);
    BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.NETWORK,
        "https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4");
    _betterPlayerController = BetterPlayerController(
      BetterPlayerConfiguration(
        fullScreenByDefault: true,
        aspectRatio: 9 / 16,
        fullScreenAspectRatio: 9 / 16,
        fit: BoxFit.contain,
        autoPlay: true,
        allowedScreenSleep: false,
        deviceOrientationsOnFullScreen: [
          DeviceOrientation.landscapeRight,
          DeviceOrientation.landscapeLeft,
          DeviceOrientation.portraitUp,
          DeviceOrientation.portraitDown
        ],
        deviceOrientationsAfterFullScreen: [
          DeviceOrientation.portraitUp,
        ],
        subtitlesConfiguration: BetterPlayerSubtitlesConfiguration(
          outlineEnabled: false,
        ),
        controlsConfiguration: BetterPlayerControlsConfiguration(
          showControls: true,
          enableSubtitles: false,
          enableQualities: false,
          enablePlaybackSpeed: true,
          enableOverflowMenu: false,
          iconsColor: Colors.white,
          fullscreenDisableIcon: Icons.arrow_back,
          fullscreenEnableIcon: Icons.arrow_back,
        ),
      ),
      betterPlayerDataSource: betterPlayerDataSource,
    );
  }

  @override
  void dispose() {
    SystemChrome.setEnabledSystemUIOverlays(
        [SystemUiOverlay.bottom, SystemUiOverlay.top]);
    super.dispose();
    WidgetsBinding.instance.removeObserver(this);
    _betterPlayerController?.dispose();
    Wakelock.disable();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    super.didChangeAppLifecycleState(state);
    switch (state) {
      case AppLifecycleState.inactive:
        if (_betterPlayerController.isPlaying()) {
          _betterPlayerController.pause();
        }
        break;
      case AppLifecycleState.resumed:
        break;
      case AppLifecycleState.paused:
        break;
      case AppLifecycleState.detached:
        break;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Column(
        children: <Widget>[
          Expanded(
            child: Center(
              child: BetterPlayer(
                controller: _betterPlayerController,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
`
**Expected behavior**
Video pause when have call comming as video_player

**Screenshots**

**Flutter doctor**
Please add flutter doctor output here.
`[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1440], locale en-US)
    • Flutter version 1.22.6 at C:\flutter
    • Framework revision 9b2d32b605 (7 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5`
**Better Player version**
- Version: 0.0.37

**Smartphone (please complete the following information):**
 - Device: iPhone 7 plus
 - OS: iOS 14.3

**Additional context**

**Comment by jhomlala** [comment]
@ThangNguyen91 Please use better formatting next time. This issue has been resolved in 0.0.60 and you're using 0.0.37 which is pretty old version.

**Comment by hosajadi** [comment]
I have version 0.0.61 of this package and this bug still exist

**Comment by NhaPCS** [comment]
@jhomlala I am facing this issue, too

**Comment by HiroshiOshiro** [comment]
Hi, Thanks for this library.

I want to stop playback when get incoming phone call. 
Is there no option to do that as of now?
If someone implement by using other library, Please share it.

I'm using better player version 0.082 (latest as of 20221024).
