### ISSUE TITLE
When Entering Full Screen New Instance of video starts

### ISSUE THREAD

**Issue by Armen-X** [jhomlala/betterplayer#65]
Hi, I really Love better player, and you rock !!! it's my favorite Video Player I am working on a project now and I ran into some issue when I am playing hls, in a page where I have a playlist like youtube and I choose different videos, when I click on another video it loads another video better than any Player out there but there is 1 problem when I click to open fullscreen it opens a new instance of the player and it shows full screen but the same video starts again and I can hear the voices still in the background I have been struggling with this for a while, I have even created my own controls and used custom_controls feature to see my controls because I am trying to bypass that 2 instances issue thing but I am very new to flutter and I am still learning it might be I have done something wrong, please have a look at it and let me know when going full screen and back you get more then 1 instance if yes can you please fix it? thank you so much for the great work

**Comment by jhomlala** [comment]
Can you provide some example? I can't reproduce it on my side.

**Comment by jhomlala** [comment]
Hi, this should be fixed with latest release (0.0.23).

**Comment by EjazAmir** [comment]
Hey, is this fixed?? I'm using 0.0.49 version and still facing this issue.

**Comment by jhomlala** [comment]
@EjazAmir Latest Better Player version is 0.0.64. Try this version.
